export const TEXT_VARIANTS = {
  display: { fontSize: 30, fontWeight: '800' },
  heading: { fontSize: 28, fontWeight: '400' },
  headingMedium: { fontSize: 28, fontWeight: '500' },
  headingSemibold: { fontSize: 28, fontWeight: '600' },
  headingExtraBold: { fontSize: 28, fontWeight: '800' },
  headingLight: { fontSize: 27, fontWeight: '300' },
  title: { fontSize: 24, fontWeight: '700' },
  titleMedium: { fontSize: 24, fontWeight: '500' },
  subtitle: { fontSize: 20, fontWeight: '500' },
  bodyLargeLight: { fontSize: 17, fontWeight: '300' },
  bodyLarge: { fontSize: 16, fontWeight: '400' },
  bodyLargeMedium: { fontSize: 16, fontWeight: '500' },
  bodyBold: { fontSize: 15, fontWeight: '700' },
  bodyMedium: { fontSize: 15, fontWeight: '500' },
  bodyBoldMedium: { fontSize: 16, fontWeight: '700' },
  bodySmall: { fontSize: 13, fontWeight: '400' },
  captionLight: { fontSize: 12, fontWeight: '300' },
  caption: { fontSize: 12, fontWeight: '400' },
  captionMedium: { fontSize: 12, fontWeight: '500' },
  label: { fontSize: 11, fontWeight: '400' },
  overline: { fontSize: 9, fontWeight: '300' },
} as const;
